export const jobsSample = [
  {
    id: 1,
    logo: "/images/company_logo.svg",
    company: "Consulting Ltd",
    jobTitle: "Software Developer",
    jobDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
    jobType: "Remote",
    skills: ["Javascript", "Java", "Angular", "Springboot"],
    location: "Lagos, Nigeria",
    deadline: "20th Dec, 2023",
    jobStatus: "Open",
  },
  {
    id: 2,
    logo: "/images/company_logo.svg",
    company: "Consulting Ltd",
    jobTitle: "Software Developer",
    jobDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
    jobType: "Remote",
    skills: ["Javascript", "Java", "Angular", "Springboot"],
    location: "Lagos, Nigeria",
    deadline: "20th Dec, 2023",
    jobStatus: "Open",
  },
  {
    id: 3,
    logo: "/images/company_logo.svg",
    company: "Consulting Ltd",
    jobTitle: "Software Developer",
    jobDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
    jobType: "Remote",
    skills: ["Javascript", "Java", "Angular", "Springboot"],
    location: "Lagos, Nigeria",
    deadline: "20th Dec, 2023",
    jobStatus: "Open",
  },
  // {
  //   id: 4,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
  // {
  //   id: 5,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
  // {
  //   id: 6,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
  // {
  //   id: 7,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
  // {
  //   id: 8,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
  // {
  //   id: 9,
  //   logo: "/images/company_logo.svg",
  //   company: "Consulting Ltd",
  //   jobTitle: "Software Developer",
  //   jobDescription:
  //     "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta ipsum diam, nec efficitur urna ultricies eu. Nam ultrices ante quis ipsum molestie gravida. Nam nec dui sodales, volutpat risus quis, dictum velit. In vel tempor est, eu bibendum nisl. Praesent porta lectus ac lacus faucibus, eget consequat leo molestie.",
  //   jobType: "Remote",
  //   skills: ["Javascript", "Java", "Angular", "Springboot"],
  //   location: "Lagos, Nigeria",
  //   deadline: "20th Dec, 2023",
  //   jobStatus: "Open",
  // },
];
